/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:f88537f6-8e33-482b-b1cf-95aee9c6e427",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_JFAgr0Lh8",
    "aws_user_pools_web_client_id": "4se7rt2k59rtuvsa9ccc4o4fkd",
    "oauth": {
        "domain": "vcrypto35cadcc2-35cadcc2-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "exp://127.0.0.1:19000/",
        "redirectSignOut": "exp://127.0.0.1:19000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://inl52lxwwzfrrnyu5ugew36cra.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
